networks:
  default:

volumes:
  images:
  logs:

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
    volumes:
      - images:/images
      - logs:/var/log/nginx
      - ./static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default
