networks:
  default:

volumes:
  images:
  logs:
  image_hosting_database:

services:
  app:
    container_name: app
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - images:/app/images
      - logs:/app/logs
    networks:
      - default
    depends_on:
      db:
        condition: service_healthy

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
    volumes:
      - images:/images
      - logs:/var/log/nginx
      - ./static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default
    depends_on:
      - app
  
  db:
    container_name: db_ih
    image: postgres:latest
    env_file:
      - ./app/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - image_hosting_database:/var/lib/porstgresql/data
    networks:
      - default
    restart: always
